# Generated by Django 4.0.2 on 2022-02-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Vaga')),
                ('salary_range', models.CharField(choices=[(1000, 'ATÉ 1000'), (2000, 'DE 1000 A 2000'), (3000, 'DE 2000 A 3000'), (9999, 'ACIMA DE 3000')], max_length=15, verbose_name='Faixa Salarial')),
                ('requirements', models.TextField(max_length=400, verbose_name='Requisitos')),
                ('minimum_schooling', models.CharField(choices=[('ens fund', 'ENSINO FUNDAMENTAL'), ('ens med', 'ENSINO MÉDIO'), ('tec', 'TECNÓLOGO'), ('ens sup', 'ENSINO SUPERIOR'), ('pos', 'PÓS/MBA/MESTRADO'), ('dout', 'DOUTORADO')], max_length=20, verbose_name='Escolaridade Mínima')),
            ],
        ),
    ]
