# Generated by Django 4.0.2 on 2022-02-12 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_alter_vacancy_minimum_schooling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_expectation', models.CharField(choices=[('Até 1000', 'ATÉ 1000'), ('De 1000 a 2000', 'DE 1000 A 2000'), ('De 2000 a 3000', 'DE 2000 A 3000'), ('Acima de 3000', 'ACIMA DE 3000')], max_length=15, verbose_name='Pretensão Salarial')),
                ('experience', models.TextField(max_length=400, verbose_name='Experiência')),
                ('last_schooling', models.CharField(max_length=20, verbose_name='Última Escolaridade')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Candidato')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.vacancy', verbose_name='Vaga')),
            ],
        ),
    ]
