# Generated by Django 4.0.2 on 2022-02-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_candidatevacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Vaga Disponivel?'),
        ),
        migrations.AlterField(
            model_name='candidatevacancy',
            name='last_schooling',
            field=models.CharField(choices=[('Ensino Fundamental', 'ENSINO FUNDAMENTAL'), ('Ensino Médio', 'ENSINO MÉDIO'), ('Tecnólogo', 'TECNÓLOGO'), ('Ensino Superior', 'ENSINO SUPERIOR'), ('Pós/MBA/Mestrado', 'PÓS/MBA/MESTRADO'), ('Doutorado', 'DOUTORADO')], max_length=20, verbose_name='Última Escolaridade'),
        ),
    ]
