# Generated by Django 4.0.2 on 2022-02-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_candidatevacancy_last_schooling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatevacancy',
            name='last_schooling',
            field=models.IntegerField(choices=[(1, 'Ensino Fundamental'), (2, 'Ensio Médio'), (3, 'Tecnólogo'), (4, 'Ensino Superior'), (5, 'Pós/MBA/Mestrado'), (6, 'Doutorado')], verbose_name='Última Escolaridade'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='minimum_schooling',
            field=models.IntegerField(choices=[(1, 'Ensino Fundamental'), (2, 'Ensio Médio'), (3, 'Tecnólogo'), (4, 'Ensino Superior'), (5, 'Pós/MBA/Mestrado'), (6, 'Doutorado')], verbose_name='Escolaridade Mínima'),
        ),
    ]
