# Generated by Django 4.0.2 on 2022-02-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_candidatevacancy_last_schooling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(max_length=1000, verbose_name='Requisitos'),
        ),
    ]
