# Generated by Django 4.0.2 on 2022-02-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('mensagem', models.TextField(max_length=400, verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
